services:
  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    command:
      sh -c "
            uvicorn app.index:app --host 0.0.0.0 --port 2000 --reload
            "
            # aerich init-db
            # aerich migrate &&
            # aerich upgrade &&

    env_file:
      - ./.env

    volumes:
      - ./:/notification-service
    depends_on:
      - notification-db

  notification-db:
    image: postgres:16.2-alpine
    volumes:
      - notification_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_NAME: ${DB_NAME:-db}
      POSTGRES_USER: ${DB_USR:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pass}
    ports:
      - ${DB_PORT:-5433}:5432

volumes:
  notification_data: