services:
  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "uvicorn app.index:app --host 0.0.0.0 --port 2000 --reload"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth-service:1000}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_SERVER: ${MAIL_SERVER:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
    env_file:
      - ./.env
    volumes:
      - ./:/notification-service:cached
    ports:
      - "2000:2000"
    user: "1000:1000"
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true